sudo: false

language: ruby

rvm:
- 2.2.2
- 2.1.6
- 2.0.0
- 1.9.3
- 1.8.7
- jruby-20mode
- jruby-21mode
- jruby
- rbx

matrix:
  allow_failures:
  - rvm: rbx


#install: script/bootstrap --without development debug
install:  script/bootstrap

script: script/test

env:

