sudo: false
language: ruby

rvm:
- 2.2.2
#- 2.1.6
#- 2.0.0
#- 1.9.2
#- 1.9.3
#- 1.8.7
#- jruby-20mode
#- jruby-21mode
- jruby
- rbx
matrix:
  allow_failures:
  #- rvm: rbx

before_install:
  - gem install bundler --version '>=1.9.5'  #  so we can be sure to set code of conduct option= false to avoid an interactive prompt
  - bundle --version
  - gem --version
  - ruby --version
  - echo $(ruby -e 'puts "RUBY_ENGINE =#{RUBY_ENGINE}="')
  - echo $(ruby -e 'puts "RUBY_PLATFORM =#{RUBY_PLATFORM}="')


script: "bundle exec rake show_rbconfig"
